# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_apiauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Auth request',
                'verbose_name_plural': 'Auth requests',
                'ordering': ('user',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='authrequest',
            unique_together=set([('user', 'timestamp')]),
        ),
    ]
